### ISSUE TITLE
Unknown parameter in input: "registeredBy"

### ISSUE THREAD

**Issue by tiagoReichert** [brentley/appmeshworkshop#118]
The bug reported in [this Issue](https://github.com/aws/aws-sdk/issues/38) seem to affect the workshop on [this step](https://www.appmeshworkshop.com/mesh_crystal/installenvoy/) when trying to describe-task-definition to afterwards register-task-definition failing with the following error message:

`Parameter validation failed:
Unknown parameter in input: "registeredBy", must be one of: family, taskRoleArn, executionRoleArn, networkMode, containerDefinitions, volumes, placementConstraints, requiresCompatibilities, cpu, memory, tags, pidMode, ipcMode, proxyConfiguration, inferenceAccelerators`

**Comment by motawy** [comment]
What worked for me was to delete extra keys such as "registeredBy", "registeredAt" and so on before the register-task-definition command.

**Comment by tiagoReichert** [comment]
Hi @motawy, I also tested the same and [opened a PR](https://github.com/brentley/appmeshworkshop/pull/119) here to change the blog post.
