### ISSUE TITLE
Cleanup section doesn't remove Amazon EKS cluster

### ISSUE THREAD

**Issue by alexpulver** [brentley/appmeshworkshop#96]
The workshop uses `eksctl` to create Amazon EKS cluster in [Run the bootstrap scripts](https://www.appmeshworkshop.com/prerequisites/bootstrapsh/) section. The cleanup of the cluster is missing in "Cleanup" chapter, and should be placed before [Delete the baseline template](https://www.appmeshworkshop.com/cleanup/cfn/) section - otherwise CloudFormation fails to delete the baseline stack due to existing EC2 instances in the VPC.

**Comment by jlbutler** [comment]
Thanks for the callout! Addressed via PR #99
